### ISSUE TITLE
ActivationException when resolving class with concrete dependency

### ISSUE THREAD

**Issue by hh19** [ninject/Ninject#194]
Ninject fails to resolve ITest in the program below. Binding Dependency class to self or changing the visibility of the constructor with the string parameter to private will fix this but this feels like something that should work without having to do any extra work.

```
using Ninject;

namespace NinjectTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var kernel = new StandardKernel();

            kernel.Bind<ITest>().To<TestImpl>();
            
            kernel.Get<ITest>();
        }
    }

    public interface ITest
    {
    }

    public class TestImpl : ITest
    {
        public TestImpl(Dependency dependency)
            : this(dependency, "Default string")
        {
        }

        public TestImpl(Dependency dependency, string str)
        {
        }
    }

    public class Dependency
    {
    }
}
```

Exception message:

Error activating string
No matching bindings are available, and the type is not self-bindable.
Activation path:
  2) Injection of dependency string into parameter str of constructor of type TestImpl
  1) Request for ITest

**Comment by nkohari** [comment]
This behavior is currently as-designed, because of how `StandardConstructorSelector` works. When activating a class with multiple constructors, the `StandardConstructorSelector` will choose the constructor with the most "bindable" parameters. A bindable parameter satisfies one of the following conditions:

1. An explicit binding has been registered for it using `kernel.Bind()`, etc.
2. The type is self-bindable, meaning it is a non-abstract class that can be instantiated.

Since `Dependency` and `String` are both self-bindable, Ninject will choose the second constructor. This problem can be avoided by annotating the constructor you want Ninject to use with the `[Inject]` attribute. If you give it this hint, it won't have to guess which constructor you want to use.

**Comment by hh19** [comment]
Actually it seems that Ninject considers `String` not self-bindable. That is why the activation fails. `String` cannot be instantiated. If it was self-bindable then surely Ninject would inject the constructor with default string.

Here is the relevant part from the exception message:

> Error activating string
> No matching bindings are available, and the **type is not self-bindable**.

It's pretty clear there is a bug here where Ninject selects unresolvable constructor when there is a resolvable one available. The way it should work is either

1. Select the constructor without string argument (consider string not self-bindable).
2. Select the constructor with string argument and inject default string (consider string self-bindable).

I would prefer the number one option because injecting empty strings seems like a bad default behavior.
