### ISSUE TITLE
Cache: possible memory leak?

### ISSUE THREAD

**Issue by ruslanmogilevskiy** [ninject/Ninject#233]
I'm struggling with a memory leak problem in our app (asp.net web api + ninject dependency resolver) and found a suspicious code in ninject`s Cache class: it has Remember method where it subscribes to the Disposed event of notifyScope but never unsubscribes from this event. The notifyScope is an ActivationBlock instance in runtime created by our NinjectDependencyResolver class. 
Our NinjectDependencyResolver mostly looks like /Ninject.Web.WebApi/blob/master/src/Ninject.Web.WebApi/NinjectDependencyResolver.cs but it **creates new instance** of NinjectDependencyScope instead of reusing it like in your NinjectDependencyResolver.cs. NinjectDependencyScope, via kernel, creates new instance of ActivationBlock that's used for each type resolution, and as a new instance of ActivationBlock is created, Cache will keep more and more subscriptions to the ActivationBlock.Disposed events.
As the Cache instance is singleton because the kernel instance, that holds link to the cache, is singleton as well:
```
public class Bootstrapper : IBootstrapper
    {
        private static IKernel kernelInstance;
```

I suspect the our memory leak's reason is happening because of Cache unsibscribed Disposed event handlers.

**Comment by BrunoJuchli** [comment]
So usually, basically, once the event is subscribed, too, the reference is the other way round:

notifyScope has a reference to Cache because notifyScope needs to inform the Cache about the Disposed event.

This will keep Cache from being collected, but it *won't* keep notifyScope from being collected.

The best way to go about solving problems like this is to use a memory profiler.

**Comment by drieseng** [comment]
No feedback.
