### ISSUE TITLE
v4.0?

### ISSUE THREAD

**Issue by davethieben** [ninject/Ninject#236]
so v4.0-alpha was released almost **2 years ago**, and there hasn't been much movement since. are there any plans of release? or roadmap? 

I'd like to use some of the 4.0 features in my ASP.NET Core projects, but there isn't even a pre-release.

**Comment by dansiegel** [comment]
>so v4.0-alpha was released almost 2 years ago
I'm not sure where a 4.0-alpha was released 2 years ago. I do see though that a 4.0-beta was released in August roughly 9 months ago though. I would echo @davethieben's question about when we might expect either a stable release?

**Comment by chezuma** [comment]
@davethieben: 

Don't know if you have seen this, I assume you have: 
https://www.nuget.org/packages/Ninject/4.0.0-beta-0134

To me it seems like this project have lost momentum, is this because the product is considered "good enough, goal of project reached" or is it loss of interest of the main developers?

Either way I really love this library, and it would be sad to see if it get discontinued.

So I echo the question regarding the release of v4 :)

**Comment by davethieben** [comment]
@chezuma yeah, I saw that, but there's no tag or branch in Github, or documentation anywhere, so I have no idea what's in it.

@scott-xu @onovotny

**Comment by BrunoJuchli** [comment]
I'm not a maintainer but I currently plan to fork Ninject for a .net standard based release "4.0" with 90% feature and interface compatibility. I plan for some design changes, like the way bindings are created, i think I'll use a read-only collection and a "unit of work" kind of approach to make changes to these. This will reflect in the interface of ninject in some places. Loading of a module could be auto-encapsulated, other use cases not so much.
If everything goes according to plan I'd welcome some feedback regarding my interface changes, so to anyone willing to chime in: would be glad if you could state so here, then i'll send you a message when I've got something going on...

**Comment by chezuma** [comment]
@BrunoJuchli, sounds cool, please keep me posted if you end up doing that .

Dont get me wrong, but it would be really great to get feedback on this thread before everyone branches the current 4.0-beta, if they dont have the time and looking for new maintainers, maybe someone would step up and take the responsibility and keep this repo alive :) 

@BrunoJuchli  @scott-xu  @onovotny

**Comment by MaximRouiller** [comment]
Castle Windsor will support .NET Core in its next release.

https://github.com/castleproject/Windsor/issues/145#issuecomment-311992256

**Comment by bayger** [comment]
Is the official v4.0-* supporting .NET Core dead?

**Comment by msnelling** [comment]
Could we get a comment either way from a maintainer on this? We'd like to know whether we should wait for .Net Core/Standard support or switch to a different library.

**Comment by scott-xu** [comment]
will do

**Comment by evil-shrike** [comment]
I'm also looking forward for any info on .net core support. is there any roadmap? 
I'm sorry, but the project looks abandoned.

>> so v4.0-alpha was released almost 2 years ago

> I'm not sure where a 4.0-alpha was released 2 years ago. 

it's the latest release here - https://github.com/ninject/Ninject/releases

**Comment by BrunoJuchli** [comment]
Due to some unforeseen circumstances and "personal problems" - just at the wrong time... I've not been able to dedicate a significant ammount of time into "re factoring" Ninject and making it ready for .net core.
I really love the Ninject API and would hate to see it dying. However, to keep it alive, I believe there would need to be major effort to be put in performance-optimizing it. The "website" use case get's more and more important, and that's where Ninject performance is very bad.
So just making it .net standard by itself would not be enough, IMO.

**Comment by magol** [comment]
please, don't let it die

**Comment by scott-xu** [comment]
3.3 beta1 is released with netstandard2.0 and without ReadOnlyKernel

**Comment by msnelling** [comment]
@scott-xu Thank you!

**Comment by davethieben** [comment]
wait a minute. what does this have to do with a 4.0 release?

**Comment by scott-xu** [comment]
@davethieben if people are using 4.0 alpha/beta, they have to change ReadOnlyKernel and KernelConfiguration back to StandardKernal.
I know it may not be the best decision to back out ReadOnlyKernel. However, to make a stable release targeting just bug fix and .net standard support is far more urgent than performance tuning. Ninject slept too long... If we continue 4.0 ReadOnlyKernel, to be honest, I don’t have confidence to make a stable release in the near future.
Hope you understand. I just want to make it progressive.
