### ISSUE TITLE
Fix resolution performance issues

### ISSUE THREAD

**Issue by Mystere** [ninject/Ninject#84]
I've seen several comments from people that Ninject is extremely slow compared to other containers.  There have also been several benchmarks that seem to support this.  For instance:

http://www.palmmedia.de/Blog/2011/8/30/ioc-container-benchmark-performance-comparison

(note that the tests have been updated to include Ninject 3.0.1.10)

Is there a problem with the way that Ninject is being benchmarked?  Or is it really that much slower than everything else?  Is there a good reason we should accept this performance?  Can we address these issues?  Is there workarounds?

Many of us love Ninject, but I will soon be working in a high performance, large transaction environment and if those tests are accurate, I may have to go with something else, unless there are ways to mitigate the problems.

I'd like to see these performance issues fixed.

**Comment by BrunoJuchli** [comment]
@scott-xu 
regarding #176 and you saying that there would be room for joining work on this "ReadOnlyKernel" feature:
What do you think regarding my earlier comments on read only kernel by doing something like ".Snapshot()" ? I think we could retain a lot of the performance improvements and still offer flexibility for all who don't want to use a readonly kernel.

Would that be an option? If so i would try getting started with an implementation. Should i base this on master or another branch?

**Comment by cr7pt0gr4ph7** [comment]
@BrunoJuchli @scott-xu 
I'm very in favor of something like `.Snapshot()`, because that's what it is really wanted. Automatic change detection would be even better, e.g. using optimistic version numbers, see below.
Most of the time in `Resolve()` is probably spent in searching for matching bindings to the constructor, and then searching for matching bindings for the parameters of those bindings, and so on.

The current process goes like this (I'm concentrating on constructor injection using `StandardProvider` for now):

1. [`KernelBase.Resolve`](https://github.com/cr7pt0gr4ph7/Ninject/blob/pull-request/old-kernel/src/Ninject/KernelBase.cs):
   * Looks for a binding that matches in the current context
   * Creates an instance of `Ninject.Activation.Context` and calls `Context.Resolve()`
2. [`Context.Resolve`](https://github.com/cr7pt0gr4ph7/Ninject/blob/pull-request/old-kernel/src/Ninject/Activation/Context.cs)
  * Determines the scope by looking at the request or, if the former has no associated scope, the matching binding (using `IBinding.ScopeCallback`, passing in the current context).
  * Lock on the scope and call `Context.ResolveInternal`
3. [`Context.ResolveInternal`](https://github.com/cr7pt0gr4ph7/Ninject/blob/pull-request/old-kernel/src/Ninject/Activation/Context.cs) (executed while a lock on the scope is held!):
   * Queries `Ninject.Activation.Caching.ICache` to get the already activated instance for the current scope
   * Gets the provider that matches the current context (using `IBinding.ProviderCallback`)
   * Call `IProvider.Create(IContext)`
4. [`StandardProvider.Create`](https://github.com/cr7pt0gr4ph7/Ninject/blob/pull-request/old-kernel/src/Ninject/Activation/Providers/StandardProvider.cs):
   * ...uses the ConstructorScorer to select an appropriate constructor, thus yielding an `ConstructorInjectionDirective`.
   * ...get the injection targets (i.e. the constructor arguments) from the `ConstructorInjectionDirective` and call `StandardProvider.GetValue` to resolve them, which in turn:
      * Looks if the context contains an `IConstructorArgument`,
      * Or, if not, calls `ITarget.ResolveWithin`.
5. [`Target.ResolveWithin`](https://github.com/cr7pt0gr4ph7/Ninject/blob/pull-request/old-kernel/src/Ninject/Planning/Targets/Target.cs)
   * Calls `IRequest.CreateChildRequest`, and
   * `IKernel.Resolve(IRequest)` to resolve the request.

So, to improve performance, many information from the steps above can be cached:

1. `KernelBase.Resolve`
   * Look for an `ICachedActivationPlan` for the given type and context, which already contains:
      * The binding to activate.
      * **The `ICachedActivationPlan` instances for the parameters required by the binding.**
2. `Context.Resolve`
   * (Use a special case for the transient scope that avoids a delegate call to `ScopeCallback` when the is always returning null anyway (e.g. via `delegate == null`)?).
   * Do not take a coarse lock here; instead, take more granular locks in `Context.ResolvIInternal`.
3. `Context.ResolveInternal`
   * For non-scoped singletons:
      * Note that locks are taken on this instance of `ICachedActivationPlan`
      * Note that the cached instance for a binding is stored in an instance field of `ICachedActivationPlan`, which is protected using the double-null-check idiom (see below):
   * For transient bindings:
      * No locking of the `cachedInstance` field needed.
   * Bindings with custom scopes (e.g. HttpContext):
      * These currently pose a problem.
4. `StandardProvider.Create`
   * Determine the constructor to be used at the time when `ICachedActivationPlan` is created.
   * For each constructor parameter, use the binding for that injection target that is already cached in the `ICachedActivationPlan`, and also represented as an `ICachedActivationPlan`.

For change detection, one could use an optimistic versioning approach, such that a counter is incremented whenever the kernel transitions from "unmodified" to "dirty". This way, binding caches (that contain instances of `ICachedActivationPlan`) can check "their" version number with the current one, and only update their data (on take a lock on the kernel's data structures) when really necessary.

The main point is to cache the activation plan for a binding, and let it contain pointers to other activation plans for other related binding, such that searches in the internal datastructures are avoided, as well as avoiding coarse locks over the whole kernel / the whole scope / a certain binding, even when viewed from different scopes.

@BrunoJuchli
I've got a version that contains the latest changes from #142, but excludes the readonly kernel, over at [https://github.com/cr7pt0gr4ph7/Ninject/tree/pull-request/old-kernel], if you want to experiment with the design as it was before the introduction of `IReadonlyKernel`.

----

### Double null check
```csharp
if (instance == null) {
    lock (this) {
        if (instance == null) {
            instance = new ...();
         }
    }
}
```

**Comment by cr7pt0gr4ph7** [comment]
One idea for realizing snapshots would be to use [**`System.Collections.Immutable`**](https://www.nuget.org/packages/System.Collections.Immutable/), smartly combining immutable collections and their builders, so that locks can be completely avoided in the fast path.

The idea would be that, at the start of the resolution operation, the current state of the kernel's data structures is stored in the `IRequest` (or `IContext`, maybe) and passed down to child resolution operations.

Modifcations of the kernel are done by swapping out the pointer to the data structure using an atomic operation (note that loading and setting variables that contain a pointer to a reference type is always done atomically according to the [CLR specification](http://www.ecma-international.org/publications/standards/Ecma-335.htm)./.object references are

Possibly problematic is the scenario of concurrent modifications, but this could be avoided by taking a lock only for threads wishing to modify the `IKernel`. The other problematic area is the resolution cache, see my comment above for more information.

**Comment by danielmarbach** [comment]
What about conditional bindings?

**Comment by danielmarbach** [comment]
Interesting read http://ayende.com/blog/164739/immutable-collections-performance

**Comment by BrunoJuchli** [comment]
Sadly enough i wasn't able to spend as much time on this topic as I'd wished. The good side, however, is that it allowed me some more time to think things over.

So in the following section there'll be some more or less coherent ramblings about the stuff. Feel free to jump to the next section to read more on my (preliminary) conclusions!

So regarding requirements, I've come to the conclusion that an interface like

    IKernel newKernel = kernel.Compact();

would be very cumbersome to maintain because the application would need to update all references to the kernel. So i think the kernel should not change but rather the binding information it uses should be changed. An interface like

    kernel.Compact();

which doesn't replace the kernel would still be an option. There'd be two options:

 - after a `Compact()` attempting to change / add bindings throws an `InvalidOperationException` (so user who want to continuously change the kernel during runtime can't make use of `Compact()`. Same goes for users who don't have a clear point-in-time where kernel buildup is complete).
 - `Compact()` is allowed to be called multiple times. Adding bindings after a `Compact()` basically "uncompacts" the kernel until the next `Compact()` is called.
  - we could also potentially perform the `Compact()` call internally instead of leaving this responsiblity to the user. Issue: When? After each added binding? After each loaded module?

in the end, i think this is a rather expensive solution to implement, because binding retrieval would need to support the "uncompacted" as well as the "compacted" state. Except of course if we create a fully transactional system where only the "commited" bindings can be used. This poses another issue with the current ninject interface: `IKernel` inherits `IBindingRoot` and `IResolutionRoot`. So the atomicity of a transaction would need to be one single binding - otherwise it's unclear what state you're retrieving a binding from (warning: such small an atomicity would be detrimental on application startup performance!). Imagine:

    class MyModule : NinjectModule
    {
        public void Load()
        {
            Bind<IFoo>().To<Foo>();
            var fooInstance = Get<IFoo>();
        }
    }

this can only work if the `Bind` is immediately commited. Here comes the next issue: is it even finished? :

        public void Load()
        {
            var syntax = Bind<IFoo>().To<Foo>();
            var fooInstance = Get<IFoo>();
            syntax.WhenInjectedInto<SomeType>();
        } 

There's actually no clear definition when a binding is *complete*!

Conclusion
--------------------
Separating "kernel usage" from "kernel buildup" phases would be beneficial because:

 - buildup: allows for more coarse transactions, which improves startup performance
 - buildup: transaction boundaries are clearly defined. It is well defined when a binding definition is complete. Once you the buildup ends, you can't change the binding any more.
 - usage: improves the "default" performance because there's no explicit calls like `Compact()` to be made to improve performance. Also you don't really have to think that much about this topic because it comes *naturally*.

How about something like:

    public interface IBIndingRoot
    {
         Load<TModule>() where TModule : NinjectModule;
         /* more overloads for loading modules */

        IBindingSyntax<T> Bind<T>();
        /* more overloads for creating bindings */
    }

    public interface InitialKernelBuilder : IBindingRoot {
        /* creates the kernel with initial binding map */
        IKernel Build(); 
    }

    public interface IKernelExpander : IBindingRoot 
    {
        /* replaces the kernel's binding map with Interlocked.Exchange */
        void Commit(); //alternative: inherit from IDisposable to enable usage of using
    }

    public interface IKernel : IResolutionRoot
    {
        IKernelExpander AddBindings();
    }

    public class InitialKernelBuilder : IInitialKernelBuilder
    {
        public InitialKernelBuilder(KernelConfiguration configuration)
        {
             // similar to new StandardKernel(config);
        }
    }

usage:

    var kernelBuilder = new InitialKernelBuilder(new KernelConfig { LoadExtensions = true });
    kernelBuilder.Load<BusyIndicationModule>();
    kernelBuilder.Load<FooModule>();
    kernelBuilder.Bind<IBar>().To<Bar>();

    var kernel = kernelBuiler.Build();

    var bar = kernel.Get<IBar>();
    bar.DoSomeBarStuff();

    var kernelExpander = kernel.AddBindings();
    kernelExpander.BInd<IDelicious>().To<Delicious>();
    kernelExpander.Commit();

    // this should throw:
    kernelExpander.Bind<IFoolicious>().To<WontDo>();

What do you guys think?

**Comment by scott-xu** [comment]
still thinking...

**Comment by scott-xu** [comment]
Hi folks, I'd propose to back out ReadOnlyKernel as it still has a long way to go.
I'm thinking to draft a release called 3.3.0 which is mainly focused on bugfix and platform update.

**Comment by BrunoJuchli** [comment]
@scott-xu 
I would agree that for now bugfix and platform update (i interpret: .net standard/.net core support) is much more important.

**Comment by Mystere** [comment]
Would it maybe make more sense to do a re-write from scratch?

**Comment by scott-xu** [comment]
@BrunoJuchli There's no breaking API change. According to Semantic Version, there's no need to bump major version.

**Comment by qstarin** [comment]
Has anyone found a registration/dependency pattern with Ninject that's performant for resolving conditional dependencies?

We have interfaces that have multiple implementations where the specific implementation resolved depends on things like configuration values that can change at any time or based on parameters in the web request. Most of these are registered ToMethod which checks a condition and resolves a specific class with IContext.Kernel.Get. Many of these are also registered InScope to the current thread or http context object.

Resolving these dependencies consumes a lot of time and literally costs us real money in increased compute resource needs. Our main application serves 20M-30M requests per day and over the years I've profiled multiple pieces of functionality in our app where Ninject resolution consumes up to 50% of CPU times.

Here's an example of the types of registrations that resolve especially slowly.

```
builder.Kernel.Bind<CacheDiagnostics>().ToSelf().InRequestOrTransientScope();
builder.Kernel.Bind<NullCacheDiagnostics>().ToSelf().InSingletonScope();
builder.Kernel.Bind<Func<ICacheDiagnostics>>()
        .ToMethod(c => {
            var ctx = c;
            return () => CacheDiagModeFromHttpContext()
                            ? ctx.Kernel.Get<CacheDiagnostics>()
                            : (ICacheDiagnostics)ctx.Kernel.Get<NullCacheDiagnostics>();
        })
        .InSingletonScope();

builder.Kernel.Bind<ICache>().ToMethod(ctx => {
    switch (CacheTypeFromHttpContext()) {
        case "redis": return ctx.Kernel.Get<IRedisCache>();
        case "memory": return ctx.Kernel.Get<IMemoryCache>();
        default: return ctx.Kernel.Get<MultiLayerCache>();
    }
}).InRequestOrTransientScope();

```

**Comment by niwrA** [comment]
Same here ...

**Comment by drieseng** [comment]
We've made great advancements in the 4.0 release cycle.
Please submit a new issue if you have specific areas that need to be improved.

**Comment by michaelaird** [comment]
Fantastic! Please publish 4.0 to NuGet and submit it here (
https://danielpalme.github.io/IocPerformance/ )  so we can see the
improvements.

**Comment by AndrewSav** [comment]
Today, in August 2020, I think we can safely assume that ninject as a whole is no longer relevant.

**Comment by Telavian** [comment]
I wouldn't say that. The project is amazing and I used it for several years.

I would say that currently there are better and easier to use tools in the
.net world.

As a whole the project still works if anyone wanted to use it.

**Comment by drieseng** [comment]
I spent quite a bit of time optimizing (see #https://github.com/ninject/Ninject/issues/276) and refactoring Ninject more than a year ago. Back then I was the only active contributor that had spare cycles, and I really needed someone to have (design) discussions with.

If another experienced dev (@scott-xu, I'm looking at you ::p) is available and there's enough interest from the community, we can surely revive the effort. I'm ok with a complete reboot.

**Comment by michaelaird** [comment]
There hasn't been a commit in 6 months. there hasn't been a release in 3 years. Even though ninject is in daily use in a lot of software (including the project I work), i think we can agree it's "done".

**Comment by Azure-devops-rest-api57** [comment]
> Has anyone found a registration/dependency pattern with Ninject that's performant for resolving conditional dependencies?
> 
> We have interfaces that have multiple implementations where the specific implementation resolved depends on things like configuration values that can change at any time or based on parameters in the web request. Most of these are registered ToMethod which checks a condition and resolves a specific class with IContext.Kernel.Get. Many of these are also registered InScope to the current thread or http context object.
> 
> Resolving these dependencies consumes a lot of time and literally costs us real money in increased compute resource needs. Our main application serves 20M-30M requests per day and over the years I've profiled multiple pieces of functionality in our app where Ninject resolution consumes up to 50% of CPU times.
> 
> Here's an example of the types of registrations that resolve especially slowly.
> 
> ```
> builder.Kernel.Bind<CacheDiagnostics>().ToSelf().InRequestOrTransientScope();
> builder.Kernel.Bind<NullCacheDiagnostics>().ToSelf().InSingletonScope();
> builder.Kernel.Bind<Func<ICacheDiagnostics>>()
>         .ToMethod(c => {
>             var ctx = c;
>             return () => CacheDiagModeFromHttpContext()
>                             ? ctx.Kernel.Get<CacheDiagnostics>()
>                             : (ICacheDiagnostics)ctx.Kernel.Get<NullCacheDiagnostics>();
>         })
>         .InSingletonScope();
> 
> builder.Kernel.Bind<ICache>().ToMethod(ctx => {
>     switch (CacheTypeFromHttpContext()) {
>         case "redis": return ctx.Kernel.Get<IRedisCache>();
>         case "memory": return ctx.Kernel.Get<IMemoryCache>();
>         default: return ctx.Kernel.Get<MultiLayerCache>();
>     }
> }).InRequestOrTransientScope();
> ```





https://stackdev.space/questions/is-it-possible-to-bind-an-interface-in-ninject-only-if-it-has-not-already-been-bound
